POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "The New Methodology",
  "author": "Martin Fowler",
  "url": "https://www.martinfowler.com/articles/newMethodology.html"
}
