DELETE http://localhost:3001/api/blogs/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTY3NzEwMzQ4OX0.jxFr3aQ38Nwjkx2e09HV6LTwTl0ZFxlHgQ1qg8zQauA
